name: Backend link

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: FTP publish
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: ${{ secrets.FTP_DIR }}
        options: "-v --delete -x ^config.php"
